(defpackage "MCL-MOP"
  (:use :cl #+:mcl :ccl)
  #+:mcl (:nicknames :mop)
  (:shadow "METAOBJECT")
  (:export 
   ;; Readers for Class Metaobjects
;   "CLASS-DEFAULT-INITARGS"      
;   "CLASS-DIRECT-DEFAULT-INITARGS"
   "CLASS-DIRECT-SLOTS"
   "CLASS-DIRECT-SUBCLASSES"
   "CLASS-DIRECT-SUPERCLASSES"
;   "CLASS-FINALIZED-P"
;   "CLASS-NAME"
   "CLASS-PRECEDENCE-LIST"
   "CLASS-PROTOTYPE"
   "CLASS-SLOTS"

   "ENSURE-CLASS"
   "ENSURE-CLASS-USING-CLASS"

   ;; Readers for Generic Function Metaobjects
;  "GENERIC-FUNCTION-ARGUMENT-PRECEDENCE-ORDER"
;   "GENERIC-FUNCTION-DECLARATIONS"
;   "GENERIC-FUNCTION-LAMBDA-LIST"
;   "GENERIC-FUNCTION-METHOD-CLASS"
;   "GENERIC-FUNCTION-METHOD-COMBINATION"
;   "GENERIC-FUNCTION-METHODS"
;   "GENERIC-FUNCTION-NAME"

   ;; Readers for Method Metaobjects

   ;; Readers for Slot Definition Metaobjects
   "SLOT-DEFINITION-ALLOCATION"
   "SLOT-DEFINITION-INITARGS"
   "SLOT-DEFINITION-INITFORM"
   "SLOT-DEFINITION-INITFUNCTION"
   "SLOT-DEFINITION-NAME"
   "SLOT-DEFINITION-TYPE"
   "SLOT-DEFINITION-READERS"
;   "SLOT-DEFINITION-LOCATION" 
   "SLOT-DEFINITION-WRITERS"

;; nicht im Standard-MOP
   "MOP-STANDARD-CLASS"
   "CANONICALIZE-DEFCLASS-OPTION"
   "CANONICALIZE-DEFCLASS-OPTIONS"
   "EFFECTIVE-SLOT-DEFINITION-CLASS"
   "DIRECT-SLOT-DEFINITION-CLASS"
   "STANDARD-EFFECTIVE-SLOT-DEFINITION"
   "STANDARD-DIRECT-SLOT-DEFINITION"))
   
