;;;-*- Syntax: Ansi-common-lisp; Base: 10; Mode: lisp; Package: cl-user -*-

;;; LispWorks definition for IPC and WWW-UTILS packages
;;;
;;; Copyright (C) 1996-1998 Harlequin Group plc.  All rights reserved.
;;;

(defpackage "IPC"
  (:export
   ;; Functions
   "IP-ADDRESS-STRING"
   "STRING-IP-ADDRESS"
   "INTERNET-ADDRESS"
   "GETDOMAINNAME"
   "GET-HOST-NAME-BY-ADDRESS"
   "%LISTEN-FOR-CONNECTIONS"
   "FIND-DETAIL-FROM-STREAM"
   "ADD-CL-HTTP-STREAM-INFO"
   "%STREAM-COPY-BYTES"
   "STREAM-BYTES-TRANSMITTED"
   "STREAM-BYTES-RECEIVED"

   ;; Condition classes
   "IPC-NETWORK-ERROR"
   "UNKNOWN-HOST-NAME"
   "UNKNOWN-ADDRESS"
   "DOMAIN-RESOLVER-ERROR"))

(defpackage "WWW-UTILS"
  (:use)
  (:export
    "FILE-NOT-FOUND"
   "DEFAULT-PATHNAME"
   "ABORT-HTTP-STREAM"
   "LOG-WINDOW"
   "NOTIFY-LOG-WINDOW"
   "EXPOSE-LOG-WINDOW"
   "COMMON-LOGFILE-NOTIFY"
   "BYTES-TRANSMITTED"
   "BYTES-RECEIVED"
   "DEFRESOURCE"
   "CLEAR-RESOURCE"
   "ALLOCATE-RESOURCE"
   "DEALLOCATE-RESOURCE"
   "USING-RESOURCE"
   "METHOD-SPECIALIZERS"
   "GENERIC-FUNCTION-METHODS"
   "CLASS-DIRECT-SUPERCLASSES"
   "NETWORK-ERROR"
   "LOCAL-NETWORK-ERROR"
   "DOMAIN-RESOLVER-ERROR"
   "REMOTE-NETWORK-ERROR"
   "CONNECTION-LOST"
   "BAD-CONNECTION-STATE"
   "CONNECTION-CLOSED"
   "UNKNOWN-HOST-NAME"
   "HOST-STOPPED-RESPONDING"
   "HOST-NOT-RESPONDING"
   "PROTOCOL-TIMEOUT"
   "CONNECTION-ERROR"
   "CONNECTION-REFUSED"
   "CHUNK-TRANSFER-ENCODING-MODE"
   "NOTE-FIRST-CHUNK"
   "NOTE-LAST-CHUNK"
   "CHUNK-TRANSFER-DECODING-MODE"
   "CHUNK-TRANSFER-DECODING-MODE-END"
   "END-OF-CHUNK-TRANSFER-DECODING"
   "CHUNK-TRANSFER-CONTENT-LENGTH"
   "TCP-SERVICE-PORT-NUMBER"
   "WITH-TIMEOUT"
   )
  (:export
    "PROCESS-ACTIVE-P"
    "PROCESS-RUN-FUNCTION"
    "PROCESS-RESET"
    "PROCESS-PRESET"
    "PROCESS-KILL"
    "PROCESS-WHOSTATE"
    "PROCESS-ENABLE"
    "PROCESS-DISABLE"
    "PROCESS-WAIT"
    "PROCESS-WAIT-WITH-TIMEOUT"
    "PROCESS-WAIT-FOR-STREAM"
    "MAKE-PROCESS"
    "PROCESS-RUN-TIME"
    "PROCESS-IDLE-TIME"
    "PROCESS-PRIORITY")
  #+LispWorks3.2
  (:import-from "CL"
   "IGNORABLE")
  #+LispWorks3.2
  (:export
    "IGNORABLE")
  #+LispWorks
  (:import-from "IPC"
   "UNKNOWN-HOST-NAME")
  #+LispWorks
  (:import-from "CLOS"
   "METHOD-SPECIALIZERS"
   "GENERIC-FUNCTION-METHODS"
   "CLASS-DIRECT-SUPERCLASSES")
  (:import-from "RESOURCES"
   "DEFRESOURCE"
   "CLEAR-RESOURCE"
   "ALLOCATE-RESOURCE"
   "DEALLOCATE-RESOURCE"
   "USING-RESOURCE")
  (:import-from "CLIM-SYS" "PROCESS-ACTIVE-P" "PROCESS-PRESET"
		"PROCESS-WHOSTATE"))

(defpackage smtp
  (:use future-common-lisp www-utils))
